[url]
url = "https://de-materials-tpcds.s3.ca-central-1.amazonaws.com/inventory.csv"
destination_folder = '/tmp'
file_name = 'inventory.csv'

[destination]
destination_folder = '/tmp'
file_name = 'inventory.csv'
